#!/usr/bin/env bash
########################################
#Nome do script	:quizTermoquimica
#Descrição:Esse quiz foi feito para ser aplicado na feria de ciências do Senac Sorocaba.
#Autor:Marco Tulio Dueñas
#######################################
pontos=0
while :
  do 
    dialog --title "Seja bem-vindo ao nosso quiz!"\
      --msgbox "Este quiz busca visar o seu conhecimento em termoquimica de uma maneira divertida!" 0 0
  #Questão 1
  resposta1=$(dialog --menu "Qual a definição correta de termoquímica" 0 0 0\
      1 'A Termoquímica estuda o calor da reação provocada pela troca de energia do meio externo com os reagentes.'\
      2 'A Termoquímica estuda o termos técnicos utilizados no ramo da química e seus derivados.' --stdout)
  #Verificando a resposta enviada  
    if [[ "$resposta1" -eq "1" ]];then
	dialog --title "Parabéns, você acertou!" --msgbox "Você acertou e ganhou 1 ponto!" 0 0 
	((pontos++))
    else
 	dialog --title "Sinto muito, você errou!" --msgbox "Você errou e não ganhou pontos!" 0 0 
    fi
  #Questão @
  resposta2=$(dialog --menu "Qual a diferença entre reações exotérmicas e endotérmicas?" 0 0 0\
      1 'Reações exotérmicas absorvem calor, e reações endotérmicas liberam calor.'\
      2 'Não existe diferença.' \
      3	'Reações exotérmicas liberam calor, e reações endotérmicas absorvem calor.'  --stdout)
    if [[ "$resposta2" -eq "3" ]];then
      dialog --title "Parabéns, você acertou!" --msgbox "Você acertou e ganhou 1 ponto!" 0 0 
      ((pontos++))
    else
      dialog --title "Sinto muito, você errou!" --msgbox "Você errou e não ganhou pontos!" 0 0 
    fi
  resposta3=$(dialog --menu "Qual das alternativas a seguir apresenta reações exotérmicas?" 0 0 0\
      1 'Queima de vela, queima de propano (gás de cozinha).'\
      2 'Água fervendo e condensação da água.' \
      3	'Combustão do álcool e gelo instantâneo.'  --stdout)
    if [[ "$resposta3" -eq "1" ]];then
      dialog --title "Parabéns, você acertou!" --msgbox "Você acertou e ganhou 1 ponto!" 0 0 
      ((pontos++))
    else
      dialog --title "Sinto muito, você errou!" --msgbox "Você errou e não ganhou pontos!" 0 0 
    fi
  resposta4=$(dialog --menu "Qual a definição de entalpia?" 0 0 0\
      1 'A entalpia é uma área da termoquímica que explica fenômenos através das leis de Tesla.'\
      2 'A entalpia é a quantiedade de energia dentro de uma reação, e a variação dela ocorre entre os produtos e os reagentes, tendo duas classificações: endotérmicas e exotérmicas' \
      3	'A entalpia, conhecida como lei de Hess, fala que a variação dela é adquirida através da soma de suas mudanças em etapas individuais'  --stdout)
    if [[ "$resposta4" -eq "2" ]];then
      dialog --title "Parabéns, você acertou!" --msgbox "Você acertou e ganhou 1 ponto!" 0 0 
      ((pontos++))
     
    else
      dialog --title "Sinto muito, você errou!" --msgbox "Você errou e não ganhou pontos!" 0 0 
    fi
	 dialog --title "Análise final"\
      --msgbox "Você concluiu o quiz, e acertou $pontos/4 questões! Muito obrigado por jogar :D" 0 0
    
done    

